### ISSUE TITLE
Can't install elasticsearch, Error autoloading yumrepo Type

### ISSUE THREAD

**Issue by mtenrero** [voxpupuli/puppet-elastic_stack#18]
Applying class 'elasticsearch' without specifying version couldn't add the RHEL repository giving this error

```
Warning: /etc/puppetlabs/code/environments/elasticprod/modules/elasticsearch/hiera.yaml: Use of 'hiera.yaml' version 4 is deprecated. It should be converted to version 5
   (file: /etc/puppetlabs/code/environments/elasticprod/modules/elasticsearch/hiera.yaml)
Warning: Defining "data_provider": "hiera" in metadata.json is deprecated.
   (file: /etc/puppetlabs/code/environments/elasticprod/modules/elasticsearch/metadata.json)
Error: Could not autoload puppet/type/yumrepo: undefined method `sensitive' for Puppet::Type::Yumrepo::Proxy_password:Class
Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/yumrepo: undefined method `sensitive' for Puppet::Type::Yumrepo::Proxy_password:Class (file: /etc/puppetlabs/code/environments/elasticprod/modules/elastic_stack/manifests/repo.pp, line: 89, column: 7) on node gules.domain.com
```
Modules Installed:
── elastic-elastic_stack (v6.2.4)
├── elastic-elasticsearch (v6.3.3)
├── puppet-archive (v3.2.0)
├── puppet-yum (v3.1.0)
├── puppetlabs-apt (v6.0.0)
├── puppetlabs-concat (v4.2.1)
├── puppetlabs-java (v3.1.0)
├── puppetlabs-stdlib (v4.25.1)
├── puppetlabs-yumrepo_core (v1.0.1)
└── richardc-datacat (v0.6.2)

**Comment by smortex** [comment]
This got overcome by events: we now have a default version and and a data type that checks it is an Integer:
https://github.com/voxpupuli/puppet-elastic_stack/blob/master/manifests/repo.pp#L19
