### ISSUE TITLE
What if I want to change apt settings elsewhere?

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-elastic_stack#36]
I have to disable the `include apt` here since it conflicts with the other settings in my environment.

```diff
diff --git a/manifests/repo.pp b/manifests/repo.pp
index 774291c..c035860 100644
--- a/manifests/repo.pp
+++ b/manifests/repo.pp
@@ -66,7 +66,7 @@ class elastic_stack::repo (
 
   case $::osfamily {
     'Debian': {
-      include apt
+      # include apt
 
       apt::source { 'elastic':
         ensure   => 'present',
```

`if ! defined (Class['apt']) {include apt}` didn't help either, since this one comes before my own settings.

**Comment by jarpy** [comment]
Does your environment configure `apt` with a resource-like declaration, like this?

```puppet
class {'apt':
  setting => 'value',
}
```
The more modern approach is to `include apt` where you need it, and set the `apt` class parameters with Hiera data. Then, `apt` can be used by any number of modules with `include`, `require`, and `contain`, and they will all get the parameters from Hiera and not create resource conflicts.

> CAUTION: Do not mix include-like and resource-like declarations for a given class. If you declare or assign a class using both styles, it can cause compilation failures.
 -- https://puppet.com/docs/puppet/7.4/lang_classes.html#lang_class_declare

**Comment by hboetes** [comment]
Hello @jarpy 
Thanks for the heads-up, I never got `hiera` working. Maybe I should give it another shot.

**Comment by jarpy** [comment]
> this kind of conflicts is where I find puppet very annoying

Absolutely. It really does get better with Hiera and `include`, though. So it's worth working towards, in my opinion. :)

This video changed my Puppet life, by the way:

https://www.youtube.com/watch?v=v9LB-NX4_KQ

It's old now, but I think it's mostly still relevant.

**Comment by jarpy** [comment]
If you're in a hurry, here's the super-relevant section:

https://youtu.be/v9LB-NX4_KQ?t=2696

**Comment by jarpy** [comment]
I also, personally, really like the "automatic parameter lookup" mentioned at 51:00, but that's a matter of taste.

**Comment by hboetes** [comment]
Awesome, looking at it right now!

**Comment by smortex** [comment]
Closing this old issue which got solved.

The roles & profile pattern says `apt` is declared in your `profile::apt`, elastic stuff is in `profile::elasticsearch` and the latest include the former one.  If all nodes that use these modules do it the same way, no need for parameters / automatic parameter lookup.
